# Site settings
title: Hassan F Bawor
url: "http://HassanFBawor.github.io/"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  This is my website, i hope you enjoy your time here.
  

# Your information
email: hassan.bawor@aims.ac.rw
author: Hassan F Bawor
avatar: "https://github.com/HassanFBawor/HassanFBawor.github.io/blob/gh-pages/Screenshot%20from%202022-11-05%2011-53-55.png?raw=true"
profile: My name is Hassan F Bawor, I am a Master candidate at the African institute for mathematical Sciences.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:your_email@example.com"
  GitHub: "https://github.com/HassanFbawor"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
